package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/stbenjam/cronex/internal/cronex"
)

func defaultDB() string {
	if p := os.Getenv("CRONEX_DB"); p != "" {
		return p
	}
	return filepath.Join(codexHome(), "cronex", "crons.sqlite3")
}

func codexHome() string {
	home := os.Getenv("CODEX_HOME")
	if home == "" {
		userHome, _ := os.UserHomeDir()
		home = filepath.Join(userHome, ".codex")
	}
	return home
}

func run(ctx context.Context, args []string, in io.Reader, out, log io.Writer) error {
	if len(args) == 0 {
		return errors.New("usage: cronex {serve|hook|config|install} [options]")
	}
	fs := flag.NewFlagSet(args[0], flag.ContinueOnError)
	fs.SetOutput(log)
	dbPath := fs.String("db", defaultDB(), "SQLite database path (or CRONEX_DB)")
	session := fs.String("session", "", "explicit session binding for manual MCP clients; Codex uses per-call threadId metadata")
	watch := fs.Bool("watch", false, "observe lifecycle state in a Codex-owned background hook")
	binary := fs.String("codex", "codex", "Codex executable used by the Stop watcher")
	home := fs.String("codex-home", codexHome(), "Codex configuration directory for install")
	trustBinary := fs.String("trust-codex", "codex", "local Codex executable used to trust installed hooks")
	if err := fs.Parse(args[1:]); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return fmt.Errorf("unexpected arguments: %v", fs.Args())
	}
	if args[0] == "install" {
		dbSpecified := os.Getenv("CRONEX_DB") != ""
		fs.Visit(func(f *flag.Flag) {
			if f.Name == "db" {
				dbSpecified = true
			}
		})
		if !dbSpecified {
			*dbPath = filepath.Join(*home, "cronex", "crons.sqlite3")
		}
		if err := install(*home, *dbPath, *binary, out); err != nil {
			return err
		}
		if err := trustInstalledHooks(ctx, *home, *dbPath, *binary, *trustBinary, out); err != nil {
			return fmt.Errorf("Cronex installed, but automatic hook trust failed: %w; fix the error and rerun install, or review the hooks with /hooks", err)
		}
		fmt.Fprintln(out, "Restart Codex to load the installed configuration.")
		return nil
	}
	path, err := filepath.Abs(*dbPath)
	if err != nil {
		return err
	}
	if args[0] == "config" {
		return writeConfig(out, path, *binary)
	}
	if args[0] == "serve" {
		s, err := cronex.Open(path, true)
		if err != nil {
			return err
		}
		defer s.Close()
		return cronex.NewServer(s, *session).Run(ctx, &mcp.StdioTransport{})
	}
	if args[0] != "hook" {
		return fmt.Errorf("unknown command %q", args[0])
	}
	payload, err := cronex.ReadHook(in)
	if err != nil {
		return err
	}
	if payload.IsSubagent() && payload.Event != "SubagentStart" {
		return nil
	}
	initialize := payload.Event == "SessionStart"
	s, err := cronex.Open(path, initialize)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	defer s.Close()
	if *watch {
		keepAlive, err := readKeepAlive(filepath.Join(*home, "cronex", "config.toml"))
		if err != nil {
			// Invalid optional settings must not disable ordinary cron delivery.
			fmt.Fprintln(log, "cronex: keepalive disabled:", err)
			keepAlive = 0
		}
		return cronex.Watch(ctx, s, payload.SessionID, cronex.CodexQueue(*binary), time.Second, keepAlive, log)
	}
	switch payload.Event {
	case "SessionStart":
		return s.EnsureSession(ctx, payload.SessionID, true)
	case "SessionEnd":
		return s.EndSession(ctx, payload.SessionID)
	case "SubagentStart":
		if payload.IsSubagent() {
			return s.DiscardSession(ctx, payload.AgentID)
		}
		return nil
	case "UserPromptSubmit":
		if err := s.BeginTurn(ctx, payload.SessionID, payload.TurnID); err != nil {
			return err
		}
		return s.AcknowledgeQueue(ctx, payload.SessionID, payload.DeliveryToken(), time.Now())
	case "PostToolUse":
		return cronex.Probe(ctx, s, payload.SessionID, out, time.Now())
	case "Stop", "Interrupt":
		return s.FinishTurn(ctx, payload.SessionID, payload.TurnID)
	default:
		return fmt.Errorf("unsupported hook event %q", payload.Event)
	}
}

func shellQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'" }

// Print an installation fragment without mutating a user's Codex settings.
func writeConfig(w io.Writer, db, codex string) error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	exe, err = filepath.EvalSymlinks(exe)
	if err != nil {
		return err
	}
	return configFor(w, exe, db, codex)
}

func configFor(w io.Writer, exe, db, codex string) error {
	command := shellQuote(exe) + " hook --db " + shellQuote(db) + " --codex " + shellQuote(codex)
	fmt.Fprintf(w, "# Generated by cronex config. Merge into your Codex config.toml.\n[mcp_servers.cronex]\ncommand = %s\nargs = [\"serve\", \"--db\", %s]\n\n", strconv.Quote(exe), strconv.Quote(db))
	for _, event := range []string{"SessionStart", "SubagentStart", "UserPromptSubmit", "Stop", "Interrupt", "PostToolUse", "SessionEnd"} {
		fmt.Fprintf(w, "[[hooks.%s]]\n[[hooks.%s.hooks]]\ntype = \"command\"\ncommand = %s\n", event, event, strconv.Quote(command))
		timeout := 5
		if event == "SessionEnd" || event == "Interrupt" {
			timeout = 3
		}
		fmt.Fprintf(w, "timeout = %d\n", timeout)
		if event == "PostToolUse" {
			fmt.Fprintln(w, "additionalContextLimit = 20000")
		}
		// The synchronous handler owns transitions. Its concurrent background
		// observer cannot change turn state, even when an older hook starts late.
		if event == "Stop" || event == "UserPromptSubmit" {
			fmt.Fprintf(w, "[[hooks.%s.hooks]]\ntype = \"command\"\ncommand = %s\nasync = true\ntimeout = 2147483647\n", event, strconv.Quote(command+" --watch"))
		}
		fmt.Fprintln(w)
	}
	return nil
}

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()
	if err := run(ctx, os.Args[1:], os.Stdin, os.Stdout, os.Stderr); err != nil {
		if !errors.Is(err, context.Canceled) {
			fmt.Fprintln(os.Stderr, "cronex:", err)
		}
		// Hooks fail open: an unavailable scheduler must never break a tool call.
		if len(os.Args) < 2 || os.Args[1] != "hook" {
			os.Exit(1)
		}
	}
}
